---
- name: Check required variables
  ansible.builtin.fail:
    msg: "Variable '{{ item }}' is not defined"
  when: item is false
  with_items: "{{ openwisp2_wireguard_required_variables }}"

- name: Import user management tasks
  ansible.builtin.import_tasks: user_management.yml
  tags: [wireguard_openwisp, user_management]

- name: Import APT tasks
  ansible.builtin.import_tasks: apt.yml
  when: ansible_distribution == "Debian" or ansible_distribution == "Ubuntu"
  tags: [wireguard_openwisp, apt]

- name: Import pip tasks
  ansible.builtin.import_tasks: pip.yml
  tags: [wireguard_openwisp, pip]

- name: Import flask tasks
  ansible.builtin.import_tasks: flask.yml
  tags: [wireguard_openwisp, flask]

- name: Import uwsgi tasks
  ansible.builtin.import_tasks: uwsgi.yml
  tags: [wireguard_openwisp, uwsgi]

- name: Import complete tasks
  ansible.builtin.import_tasks: complete.yml
  tags: [wireguard_openwisp, complete]
