---
- name: Verify
  hosts: all
  become: true
  gather_facts: false

  vars_files:
    - ../vars/main.yml
    - ../../vars/main.yml

  pre_tasks:
    # Overwriting update_wireguard.sh script to allow testing the Flask app
    # since the update_wireguard.sh will try to download VPN configuration f
    # rom OpenWISP which is not present here.
    - name: Copy update_wireguard.sh
      ansible.builtin.copy:
        content: |
          #!/bin/bash
          exit 0
        dest: "{{ openwisp2_wireguard_path }}/update_wireguard.sh"
        group: "{{ openwisp_group }}"
        mode: "0750"
      tags: [wireguard, updater_script]
    - name: Reload supervisor
      ansible.builtin.command: supervisorctl reload
      changed_when: true
  tasks:
    - name: Verify configured OpenWISP user and group
      block:
        - name: Get configured OpenWISP user
          ansible.builtin.getent:
            database: passwd
            key: "{{ openwisp_user }}"
        - name: Get configured OpenWISP group
          ansible.builtin.getent:
            database: group
            key: "{{ openwisp_group }}"
        - name: Assert configured OpenWISP user belongs to configured group
          ansible.builtin.assert:
            that:
              - ansible_facts.getent_passwd[openwisp_user][2] == ansible_facts.getent_group[openwisp_group][1]

    - name: Verify configured OpenWISP paths and permissions
      block:
        - name: Stat WireGuard directory
          ansible.builtin.stat:
            path: "{{ openwisp2_wireguard_path }}"
          register: wireguard_path_stat
        - name: Stat update_wireguard.sh
          ansible.builtin.stat:
            path: "{{ openwisp2_wireguard_path }}/update_wireguard.sh"
          register: update_wireguard_stat
        - name: Stat configured sudoers file
          ansible.builtin.stat:
            path: "/etc/sudoers.d/{{ openwisp_group }}"
          register: openwisp_sudoers_stat
        - name: Assert configured OpenWISP paths and permissions
          ansible.builtin.assert:
            that:
              - wireguard_path_stat.stat.gr_name == openwisp_group
              - update_wireguard_stat.stat.gr_name == openwisp_group
              - openwisp_sudoers_stat.stat.exists
              - openwisp_sudoers_stat.stat.mode == "0440"

    - name: Test Flask WireGuard Updater
      block:
        - name: Test with correct auth token
          ansible.builtin.uri:
            url: >-
              https://{{ inventory_hostname }}:{{ openwisp2_wireguard_flask_port
              }}{{ openwisp2_wireguard_flask_endpoint }}?key={{ openwisp2_wireguard_flask_key }}
            validate_certs: false
            method: "POST"
            status_code: [200]
          register: _result
          until: _result.status == 200
          retries: 5
          delay: 5
        - name: Test with wrong auth token
          ansible.builtin.uri:
            url: >-
              https://{{ inventory_hostname }}:{{ openwisp2_wireguard_flask_port
              }}{{ openwisp2_wireguard_flask_endpoint }}?key=wrong-auth-token
            validate_certs: false
            method: "POST"
            status_code: [403]
      rescue:
        - name: Get Flask log
          ansible.builtin.command: "tail -n 500 {{ openwisp2_wireguard_path }}/vpn_updater.log"
          register: flask_log
          changed_when: false
        - name: Show Flask log
          ansible.builtin.debug:
            var: flask_log
          failed_when: true
