---

openwisp2_wireguard_controller_url: "https://example.com"
openwisp2_wireguard_vpn_uuid: "vpn-uuid"
openwisp2_wireguard_vpn_key: "vpn-key"
openwisp2_wireguard_flask_key: "flask-key"
openwisp2_wireguard_directory: /opt/openwisp2/wireguard
openwisp2_wireguard_flask_endpoint: '/trigger-update'
openwisp2_wireguard_flask_port: '8081'
